/**
 * [INPUT]: 依赖 CLI 命令参数与服务端原生构建/发布字段
 * [OUTPUT]: 对外提供平台、含 channelId/bundleHash 的原生包体、发布与 Provider 共享契约
 * [POS]: CLI 公共模型层，兼容旧数字 ID 与独立服务 UUID，并为上传前版本组检查保留内容身份
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
declare global {
  var NO_INTERACTIVE: boolean | undefined;
  var USE_ACC_OSS: boolean | undefined;
}

export interface Session {
  token: string;
}

export type Platform = 'ios' | 'android' | 'harmony';

export interface Package {
  // Legacy SaaS IDs are numeric; the independent service uses UUID strings.
  id: string | number;
  name: string;
  version?: string;
  status?: string;
  appId?: string;
  appKey?: string;
  versionName?: string | number | null;
  channelId?: string;
  bundleHash?: string;
  hash?: string;
  /** Opaque UUID generated by the native build; never parsed as a number. */
  buildTime?: string | null;
  channel?: string;
  deps?: Record<string, string> | string | null;
}

export interface Version {
  id: string | number;
  hash: string;
  name: string;
  packages?: Package[];
  deps?: Record<string, string> | string | null;
  /** storage key of the archived source map (absent when published without one) */
  sourceMapKey?: string;
}

export interface CommandContext<
  TOptions extends Record<string, unknown> = Record<string, unknown>,
> {
  args: string[];
  options: TOptions;
  platform?: Platform;
  appId?: string;
  session?: Session;
}

export interface CommandResult {
  success: boolean;
  data?: unknown;
  error?: string;
}

export interface BundleOptions {
  dev?: boolean;
  platform?: Platform;
  bundleName?: string;
  entryFile?: string;
  output?: string;
  sourcemap?: boolean;
  taro?: boolean;
  expo?: boolean;
  rncli?: boolean;
  hermes?: boolean;
  /** 'auto' (default) | 'none' | path to a .hbc/.ppk/.apk/.ipa used as hermesc -base-bytecode */
  hermesBase?: string;
  /** run the disassembly equivalence check after a base compile (default true) */
  verifyHermesBase?: boolean;
  /** pass --reset-cache to Metro (default true); false reuses its transform cache */
  resetCache?: boolean;
  sentryRelease?: string;
  sentryDist?: string;
  /** publish to this app instead of the one selected in the config file */
  appId?: string;
  /** selected-app config file (default: update.json) */
  config?: string;
}

export interface PublishOptions {
  filePath?: string;
  /** path of the final source map to archive with the version */
  sourcemap?: string;
  platform?: Platform;
  name?: string;
  description?: string;
  metaInfo?: string;
  diffFromHash?: string;
  packageId?: string;
  packageVersion?: string;
  /** Default channel code; targets.json can override it for each deployment target. */
  channel?: string;
  /** JSON file containing independent channel × native-version targets. */
  targets?: string;
  /** Exact deployment ids returned by standalone publish for a safe retry. */
  deploymentIds?: string;
  /** Legacy alias for deploymentIds. */
  releaseIds?: string;
  minPackageVersion?: string;
  maxPackageVersion?: string;
  packageVersionRange?: string;
  /** Global rollout fallback; target.rollout wins, then this value, then 100%. */
  rollout?: number | string;
  dryRun?: boolean;
  appId?: string;
  config?: string;
}

export interface UploadOptions {
  platform?: Platform;
  filePath: string;
  appId?: string;
  appKey?: string;
  version?: string;
  /** Assertion only; never overrides the channel embedded in the native package. */
  channel?: string;
  config?: string;
}

export interface UpdateVersionOptions {
  platform?: Platform;
  packageId?: string;
  packageVersion?: string;
  channel?: string;
  minPackageVersion?: string;
  maxPackageVersion?: string;
  packageVersionRange?: string;
  rollout?: number | string;
  dryRun?: boolean;
}

export interface SymbolicateOptions {
  /** stack trace file ('-' for stdin) */
  stackFile?: string;
  /** update hash of the running version (from getUpdateMetadata().currentVersion) */
  hash?: string;
  versionId?: string;
  platform?: Platform;
  appId?: string;
  config?: string;
  /** write the symbolicated stack here instead of stdout */
  output?: string;
}

export interface CLIProvider {
  bundle: (options: BundleOptions) => Promise<CommandResult>;
  publish: (options: PublishOptions) => Promise<CommandResult>;
  symbolicate: (options: SymbolicateOptions) => Promise<CommandResult>;
  upload: (options: UploadOptions) => Promise<CommandResult>;

  createApp: (name: string, platform: Platform) => Promise<CommandResult>;
  listApps: (platform?: Platform) => Promise<CommandResult>;
  getSelectedApp: (
    platform?: Platform,
    config?: string,
  ) => Promise<{ appId: string; platform: Platform }>;

  listVersions: (appId: string) => Promise<CommandResult>;
  updateVersion: (
    appId: string,
    versionId: string,
    updates: UpdateVersionOptions,
  ) => Promise<CommandResult>;
  listPackages: (appId: string) => Promise<CommandResult>;

  getPlatform: (platform?: Platform) => Promise<Platform>;
  loadSession: () => Promise<Session>;
}
